FROM mysql:8.0

# Set the environment variables
ENV MYSQL_ROOT_PASSWORD=1234
ENV MYSQL_DATABASE=api_ideas

# Copy the database file into the container at /docker-entrypoint-initdb.d/
COPY ./db.sql /docker-entrypoint-initdb.d/

# Just a script to help re-populate the database if needed.
COPY ./populatedb.sh /db_initialize/

# Expose the MySQL port
EXPOSE 3306
# Start the MySQL server
