services:
  database:
    build:
      context: ./
      dockerfile: Dockerfile_db
    image: database_image
    container_name: database
    ports:
      - 3307:3306
    networks:
      - shared_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    depends_on:
      database:
        condition: service_healthy
    build:
      context: ./
      dockerfile: Dockerfile_api
    image: api_image
    working_dir: /usr/src/TasksAPI
    container_name: api
    restart: unless-stopped
    ports:
      - 8080:8080
    
    networks:
      - shared_network
    

networks:
  shared_network:
    driver: bridge