FROM node:14

RUN mkdir -p /usr/src/TasksAPI
WORKDIR /usr/src/TasksAPI

RUN apt update && apt upgrade -y && apt install -y bash

COPY package.json .
RUN npm install

COPY . .

EXPOSE 8080

CMD [ "npm", "start" ]
